// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfred_mod.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFred_mod_CfgInitialize(XFred_mod *InstancePtr, XFred_mod_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFred_mod_Start(XFred_mod *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XFred_mod_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XFred_mod_IsDone(XFred_mod *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XFred_mod_IsIdle(XFred_mod *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XFred_mod_IsReady(XFred_mod *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XFred_mod_EnableAutoRestart(XFred_mod *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFred_mod_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XFred_mod_DisableAutoRestart(XFred_mod *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFred_mod_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_AP_CTRL, 0);
}

u32 XFred_mod_Get_id(XFred_mod *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_ID_DATA);
    return Data;
}

u32 XFred_mod_Get_id_vld(XFred_mod *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_ID_CTRL);
    return Data & 0x1;
}

void XFred_mod_Set_mem_in(XFred_mod *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFred_mod_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_MEM_IN_DATA, Data);
}

u32 XFred_mod_Get_mem_in(XFred_mod *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_MEM_IN_DATA);
    return Data;
}

void XFred_mod_Set_mem_out(XFred_mod *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFred_mod_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_MEM_OUT_DATA, Data);
}

u32 XFred_mod_Get_mem_out(XFred_mod *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_MEM_OUT_DATA);
    return Data;
}

u32 XFred_mod_Get_args_BaseAddress(XFred_mod *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_bus_BaseAddress + XFRED_MOD_CTRL_BUS_ADDR_ARGS_BASE);
}

u32 XFred_mod_Get_args_HighAddress(XFred_mod *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Ctrl_bus_BaseAddress + XFRED_MOD_CTRL_BUS_ADDR_ARGS_HIGH);
}

u32 XFred_mod_Get_args_TotalBytes(XFred_mod *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XFRED_MOD_CTRL_BUS_ADDR_ARGS_HIGH - XFRED_MOD_CTRL_BUS_ADDR_ARGS_BASE + 1);
}

u32 XFred_mod_Get_args_BitWidth(XFred_mod *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFRED_MOD_CTRL_BUS_WIDTH_ARGS;
}

u32 XFred_mod_Get_args_Depth(XFred_mod *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFRED_MOD_CTRL_BUS_DEPTH_ARGS;
}

u32 XFred_mod_Write_args_Words(XFred_mod *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XFRED_MOD_CTRL_BUS_ADDR_ARGS_HIGH - XFRED_MOD_CTRL_BUS_ADDR_ARGS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Ctrl_bus_BaseAddress + XFRED_MOD_CTRL_BUS_ADDR_ARGS_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XFred_mod_Read_args_Words(XFred_mod *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XFRED_MOD_CTRL_BUS_ADDR_ARGS_HIGH - XFRED_MOD_CTRL_BUS_ADDR_ARGS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Ctrl_bus_BaseAddress + XFRED_MOD_CTRL_BUS_ADDR_ARGS_BASE + (offset + i)*4);
    }
    return length;
}

u32 XFred_mod_Write_args_Bytes(XFred_mod *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XFRED_MOD_CTRL_BUS_ADDR_ARGS_HIGH - XFRED_MOD_CTRL_BUS_ADDR_ARGS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Ctrl_bus_BaseAddress + XFRED_MOD_CTRL_BUS_ADDR_ARGS_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XFred_mod_Read_args_Bytes(XFred_mod *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XFRED_MOD_CTRL_BUS_ADDR_ARGS_HIGH - XFRED_MOD_CTRL_BUS_ADDR_ARGS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Ctrl_bus_BaseAddress + XFRED_MOD_CTRL_BUS_ADDR_ARGS_BASE + offset + i);
    }
    return length;
}

void XFred_mod_InterruptGlobalEnable(XFred_mod *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFred_mod_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_GIE, 1);
}

void XFred_mod_InterruptGlobalDisable(XFred_mod *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFred_mod_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_GIE, 0);
}

void XFred_mod_InterruptEnable(XFred_mod *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_IER);
    XFred_mod_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XFred_mod_InterruptDisable(XFred_mod *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_IER);
    XFred_mod_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XFred_mod_InterruptClear(XFred_mod *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFred_mod_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XFred_mod_InterruptGetEnabled(XFred_mod *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_IER);
}

u32 XFred_mod_InterruptGetStatus(XFred_mod *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFred_mod_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XFRED_MOD_CTRL_BUS_ADDR_ISR);
}

